config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:index, :show]
  get 'contacto/forn_contactenos'
  
 

  root 'static_pages#home2'
  get '/home' => 'static_pages#home'
  get '/contactenos' => 'static_pages#contactenos'
  
  get 'acercade' => 'static_pages#about'

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/noticia.rb
class Noticia < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  
  def full_name
    if self.name.blank?
      self.email
    else
      self.name
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?

protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name,:last_name, :email, :password) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :date_of_birth,:avatar) }
        end
        
end

app/controllers/contacto_controller.rb
class ContactoController < ApplicationController
  def forn_contactenos
    @nombre = params[:nombre]
    
    @email= params[:email]
   
  end
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  def new
  end

  def edit
  end

  def delete
  end
  
  def index
  end
end

app/controllers/noticias_controller.rb
class NoticiasController < ApplicationController
  def new
  end

  def edit
  end

  def delete
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home2
  end
  
  def contactenos
  end
  
  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
    
    def show
        @user = User.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def resource_name
      :user
    end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/contactenos_helper.rb
module ContactenosHelper
end

app/helpers/contacto_helper.rb
module ContactoHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/noticias_helper.rb
module NoticiasHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacto/forn_contactenos.html.erb
<% provide(:title, "Contacto") %> 
 <div class="container" id="about">
     <head>
    <div class="head">
            <h3>CONTACTO</h3>
            
            </br>
    </div>   
    </head>
<div class="otrascosas">
    <div class="imagen"><img src="/logo TIP.jpg" width="200" height="200"></div>
    <div class="info">
                     <ul class="nav"><li><p>PAYSANDÚ</p></li><br> <li> 
                         <p>Coordinadora: Ana Iruleguy <tipay.2009@gmail.com></p></li><br>
                                    <li><p>Centro Universitario de Paysand&uacute; (CUP)
                                           Direcci&oacute;n: Florida 1051
                                           Teléfonos: 472.20221 - 472.22291 - 472.38342</p></li><br>
                                   <li><p>Instituto Tecnol&oacute;gico Superior de Paysand&uacute; (ITSP)
                                          Direcci&oacute;n: Sarand&iacute; 1138
                                          Teléfonos: 472.29685 - 472.42917</p></li><br>
                                   <li><p>UTU Central - Coordinaci&oacute;n Ejecutiva de Tecnélogos</p></li><br>
                                   <li><p>Mario Furest <coordinaciontecnologos@gmail.com>
                                          Karina Giovanazzi <secretcoordinaciontecnologos@gmail.com>
                                          Oficina Cero - San Salvador 1674 - Montevideo
                                          Tels: 2419.8488 - 2412.2859 int. 23</p></li><br>
                                   <li> <p>Comisi&oacute;n de Carrera</p></li><br>
                                   <li><p>Paysand&uacute; :
                                   <ul class="nav"><li><p>Eduardo Demichelis (UTU)</p></li><li><p>Pedro Etchemendy (UDELAR)</p></li><li><p>Pablo Ledesma (UTU)</p></li><li><p>Gast&oacute;n Notte (UDELAR)</p></li></ul></p>
</li> 
           </li>

</ul>
</div> </div>
    <div class="mostrar">
         <h1>Contacto <%= @nombre %></h1><br>
        <form class="form-inline">
            <div class="input-control text" data-role="input-control">
      Nombre  :&nbsp;&nbsp;&nbsp;<input type="text" name="nombre" class="textfield">
      </div></br>
      
        <div class="input-control text" data-role="input-control">
      Correo  :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" class="textfield">
      </div></br>
      
        <div class="input-control text" data-role="input-control">
      Asunto  :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" class="textfield">
      </div></br>
      
        <div class="input-control text" data-role="input-control">
     Mensaje  :&nbsp;&nbsp;&nbsp;<textarea name="area" class="textarea"></textarea>
      </div></br>
      
    
   <div class="input-control text" data-role="input-control">
    
         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input type="submit" class="btn-primary" value="Enviar">
           </div> 
        </form>
    </div>                                                                 
</div>

app/views/event/delete.html.erb
<h1>Event#delete</h1>
<p>Find me in app/views/event/delete.html.erb</p>

app/views/event/edit.html.erb
<h1>Event#edit</h1>
<p>Find me in app/views/event/edit.html.erb</p>

app/views/event/new.html.erb
<h1>Event#new</h1>
<p>Find me in app/views/event/new.html.erb</p>

app/views/layouts/_cabezal.html.erb
<!--Este cabezal es el cl&aacute;sico-->
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
  <div class="container topnav">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("logo.png", alt: " "), root_path %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
            
            <li>
                <a href="#about">Acerca de</a>
            </li>
            <li>
                <a href="#services">Servicios</a>
            </li>
            <li>
                <a href="#contact">Contacto</a>
            </li>
                
            <% if current_user %>
                <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
                <li><%= link_to 'Editar Perfil',edit_user_registration_path %></li>
                <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
            <% else %>
                <li><%= link_to 'Login', new_user_session_path %></li>
            <% end %>
        </ul>
    </div>
  </div>
</nav>

app/views/layouts/_cabezal2.html.erb
<!-- COMIENZO DE HEADER -->
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
    <div class="container topnav">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to image_tag("logo.png", alt: " "), root_path %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                
                <% if current_user %>    
                    <% if current_user.role==1 %>
                        <li>    
                            <a href="#about">Bienvenido Admin</a>
                        </li>
                         <li>
                            <%= link_to 'Members', users_path %>
                        </li>
                    <% else %>
                        <li>    
                            <a href="#about">Bienvenido Alumno</a>
                        </li>
                    <%end%>
                    
                <%end %>
                
                <li>
                    <a href="#about">Nosotros</a>
                </li>
                <li>
                    <a href="#services">Servicios</a>
                </li>
                <li>
                    <a href="#contact">Contacto</a>
                </li>
                <% if current_user %>
                    <li>
                        <%= link_to 'Editar Perfil' ,edit_user_registration_path, class:'btn' %>
                    </li>
                    
                    <li>
                        <%= link_to 'Logout', destroy_user_session_path, method: :delete,  class:'btn' %>
                    </li>
                    
                    <li class="round-image-50">
                        <%= image_tag(current_user.avatar.url(:thumb)) %>
                    </li>

                <% else %>
                    <li>
                        <a href="#myModalIn" class="btn fa fa-sign-in" data-toggle="modal"> Entrar</a>
                        <!--%= link_to 'Login', new_user_session_path %-->
                    </li>
                    <li>
                        <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
                            <a href="#myModalSignUp" class="btn fa fa-sign-in" data-toggle="modal"> Registrar</a>
                        <% end -%>
                    </li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav> <!--Fin de HEADER-->


   
    <!-- Modal HTML -->
      <div id="myModalOut" class="modal fade">

          <div class="modal-dialog">

              <div class="modal-content">

                  <div class="modal-header">

                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

                      <h4 class="modal-title">Confirmacion</h4>

                  </div>

                  <div class="modal-body">

                      <p>Est&aacute; seguro que desea Cerrar sesi&oacute;n?</p>

                  </div>

                  <div class="modal-footer">

                      <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>

                      <input type="submit" value="Log out" id="logoutUP" name="logoutUP" class="form-control btn btn-danger">

                  </div>

              </div>

          </div>

      </div>
    
    
    <!--Modal de Log In-->
    <div id="myModalIn" class="modal fade">
    
      <div class="modal-dialog">
    
          <div class="modal-content">
    
              <div class="modal-header">
    
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    
                  <h4 class="modal-title">Log In</h4>
    
              </div>
                <%= form_for(resource, as: resource_name, url: session_path(resource_name), html: {class: 'form-horizontal'}) do |f| %>
              <div class="modal-body">
                  
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2">
                                <%= f.label :email %>
                                
                                    <%= f.email_field :email, autofocus: true , required:"", placeholder:'email@email.xxx', type:'text' ,class: "form-control" %>
                                
                            </div>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2">
                                <%= f.label :password, "Contrase&ntilde;a"%>
                                
                                    <%= f.password_field :password, autocomplete: "off", required:"", placeholder:'Password' ,class: "form-control" %>
                                
                            </div>
                        </div>
                    </div>
                    
                    <% if devise_mapping.rememberable? -%>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-8 col-md-offset-2">
                                    <%= f.check_box :remember_me %>
                                    <%= f.label :remember_me, "Recúerdame" %>
                                </div>
                            </div>
                        </div>
                      <% end -%>
               
                    </div>
    
              <div class="modal-footer">
    
                  <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
    
                  <%= f.submit "Ingresar", class: 'btn btn-primary' %>
    
              </div>
            <% end %>
          </div>
    
      </div>
    
    </div>
    
    <!-- Modal de registro -->
    <div id="myModalSignUp" class="modal fade">

          <div class="modal-dialog">

              <div class="modal-content">

                  <div class="modal-header">

                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

                      <h4 class="modal-title">Registro de Usuario</h4>

                  </div>
                <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: {class: 'form-horizontal'}) do |f| %>
                  
                
                    <!--el cuerpo del modal-->
                    
                    <div class="modal-body">

                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2">
                                <%= f.label :name, "Nombre" %>
                                <%= f.text_field :name, class: "form-control",autofocus: true %>
                            </div>
                        </div>
                    </div>
                      
                      
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2">
                                <%= f.label :last_name, "Apellido" %>
                                <%= f.text_field :last_name, class: "form-control",autofocus: true %>
                            </div>
                        </div>
                    </div>
                      
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2">
                                <%= f.label :email %>
                                <%= f.email_field :email, required:"", placeholder:"ejemplo@ejemplo.xxx", class: "form-control", autofocus: true %>
                            </div>
                        </div>
                    </div>

                      <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
                        <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
                      <% end %>
                    
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2"> 
                                <%= f.label :password, "Contraseña"%>
                                <%= f.password_field :password, required:"", placeholder:"Minimo 8 caracteres",autocomplete: "off", class: "form-control" %>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2"> 
                            <%= f.label :Confirmar_Contraseña%>
                            <%= f.password_field :password_confirmation,  required:"", placeholder:"Minimo 8 caracteres", autocomplete: "off", class: "form-control" %>
                            </div>
                        </div>
                    </div>

                  </div>

                    <div class="modal-footer">
    
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                            
                        <%= f.submit "Registrar", class: "btn btn-primary" %>
                    </div>
                  <% end %>

              </div>

          </div>

      </div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= value %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <%= link_to "Home", root_path %>
                            
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#about">Nosotros</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#services">Servicios</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#contact">Contacto</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Tecn&oacute;logo en Inform&aacute;tica Paysand&uacute; 2015. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
        <title>Demo</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
  <body>

  <%= render 'layouts/cabezal2' %>
  <br>
  <%= render 'layouts/flash_messages' %>
  <%= render 'layouts/menu' %>

  
  <%= yield %>
  
  <%= render 'layouts/footer' %>

  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "Acerca del Tecn&oacute;logo") %>

<div class="row body">
    
    <div class="col-md-6">
        
        <div class="col-lg-12 text-center">
            <h2 class="section-heading">
                Acerca del Tecn&oacute;logo
            </h2>
            
            <p>
                <b>Duraci&oacute;n: </b>3 a&ntilde;os / 6 semestres
            </p>
            
            <p>
                <b>Requisitos de ingreso: </b>Pueden ingresar a la carrera tanto egresados del “Bachillerato Tecnol&oacute;gico de Procesamiento 
                y Mantenimiento Inform&aacute;tico”, de la “Ense&ntilde;anza Media Tecnol&oacute;gica en Inform&aacute;tica” y de los “Bachilleratos de Educaci&oacute;n 
                Secundaria” que habiliten el ingreso a la Facultad de Ingenier&iacute;a.
            </p>
            
            <p>
                <b>Perfil de egreso:</b>El Tecn&oacute;logo en Inform&aacute;tica ser&aacute; capaz de desarrollar sistemas de pequeño y mediano porte y podr&aacute; integrarse a grupos de desarrollo de proyectos de porte superior. 
                Contar&aacute; con la habilidad de construir y evaluar soluciones inform&aacute;ticas abarcando las tareas de construcci&oacute;n, pruebas y documentaci&oacute;n, integrando eventualmente distintas tecnolog&iacute;as.
                La carrera de se dicta en forma conjunta entre la Universidad de la Rep&uacute;blica (UdelaR) y la Administraci&oacute;n Nacional de la Educaci&oacute;n P&uacute;blica (ANEP). En Paysand&uacute; los cursos se desarrollan en las instalaciones del Puerto Digital Regional (Paysand&uacute; Innova).
            </p>
            
        </div>
    </div> 
    
    <div class="col-md-6">
        <img class="img-responsive" src="../Inova.jpg" alt="" >
    </div>
    
    
</div>

app/views/static_pages/contactenos.html.erb
<% provide(:title, "Contacto") %> 


    
<body>
    
<div class="row body">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Cont&aacute;ctenos</h2>
                    <h3 class="section-subheading text-muted">P&oacute;ngase en contacto con el tecn&oacute;logo.</h3>
                </div>
            </div>
            
            </br>
            </br>
            
            <div class="row">
                <div class="col-lg-12">
                    <form name="sentMessage" id="contactForm" novalidate="">
                        <div class="row">
                            <div class="col-md-6">
                                
                                <div class="form-group">
                                   <input type="text" class="form-control" placeholder="Ingrese nombre *" id="name" required="" data-validation-required-message="Por favor ingrese su nombre.">
                                    <p class="help-block text-danger"></p>
                                </div>
                                
                                <div class="form-group">
                                    <input type="email" class="form-control" placeholder="Ingrese e-mail *" id="email" required="" data-validation-required-message="Por favor ingrese su e-mail.">
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="form-group">
                                    <input type="tel" class="form-control" placeholder="Ingrese asunto *" id="asunto" required="" data-validation-required-message="Por favor ingrese su asunto.">
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <textarea class="form-control" placeholder="Ingrese mensaje *" id="message" required="" data-validation-required-message="Por favor ingrese el mensaje."></textarea>
                                    <p class="help-block text-danger"></p>
                                
                                <div class="col-lg-12 text-center">
                                <h5 class="section-subheading text-muted">Coordinadora: <font color="Black">Ana Iruleguy</font></h5>
                                <div  style="margin-top: 5px;"><i class="glyphicon glyphicon-envelope"></i> tipay.2009@gmail.com</div>
                                <div  style="margin-top: 5px;"><i class="glyphicon glyphicon-home"></i> Leandro G&oacute;mez y 33 Orientales S/N.</div>
                                
                                
                                
                                </div>
                                
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="col-lg-12 text-center">
                                <div id="success"></div>
                                <button type="submit" class="btn btn-primary">Enviar mensaje</button>
                            </div>
                            <br>
                        </div>
                    </form>
                </div>
            </div>
            
            
        </div>
       
       <br>
       <div>
       
                <!-- Embedded Google Map -->
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3371.7636080539423!2d-58.085891419498715!3d-32.318204022875015!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0000000000000000%3A0xcee1009272710a0c!2sCentro+MEC+Paysand%C3%BA!5e0!3m2!1ses-419!2suy!4v1429590955312" width="100%" height="500px" frameborder="0" style="border:0"></iframe>
        
      </div>
    
    </div>

</body>

app/views/users/index.html.erb
<div class="container">
    <div class="users row">
        <% @users.each do |user| %>
        <div class="panel panel-default">
            <%= link_to user_path(user) do %>
            <div class="panel-body">
                <%= image_tag(user.avatar.url(:medium)) %>
                <p><%= user.full_name %></p>
            </div>
            <% end %>
        </div>
        <% end %>
    </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Iniciar Sesion", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Registro de Usuario", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Olvido su contraseña?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="row profile">
    <div class="col-sm-4 col-md-3">
        
        <h1><%= @user.full_name %></h1>
        <ul>
            <%= content_tag(:li, ("Nombre: " + @user.name)) unless @user.name.blank? %>
            <%= content_tag(:li, ("Edad: " + distance_of_time_in_words(Time.now, @user.date_of_birth) + " años")) unless @user.date_of_birth.blank? %>
        </ul>
    </div>
    
</div>



<!-- lo que hace el segundo content_teg es resar la fecha actual con la de nacimiento y nos la edad, magia chavall -->